# Generated by Django 4.2.3 on 2023-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='Problem Name', max_length=10, unique=True),
        ),
    ]
