# Generated by Django 4.2.3 on 2023-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correct_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.TextField(default=''),
        ),
    ]
