# Generated by Django 4.2.3 on 2023-08-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(default='Problem Name', max_length=50, unique=True),
        ),
    ]
