# Generated by Django 4.2.3 on 2023-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_correct_output_problem_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
