# Generated by Django 4.2.3 on 2023-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.TextField(),
        ),
    ]
