# Generated by Django 4.2.3 on 2023-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(choices=[(1, '1 second'), (2, '2 seconds'), (3, '3 seconds'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds')], default=5),
        ),
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.CharField(default='0', max_length=25),
        ),
    ]
