# Generated by Django 4.2.3 on 2023-08-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
