# Generated by Django 4.2.3 on 2023-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_problem_correct_output_remove_problem_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='num_tests',
            field=models.IntegerField(default=1),
        ),
    ]
