# Generated by Django 4.2.3 on 2023-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_constraints_alter_problem_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template',
            field=models.TextField(default=''),
        ),
    ]
