# Generated by Django 4.2.3 on 2023-08-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_remove_problem_number_of_testcases_problem_num_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='num_tests',
        ),
    ]
